In [1]:
import pandas as pd

In [2]:
indian_wether = pd.DataFrame({
    "city": ["mumbai","delhi","banglore"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})

In [3]:
print(indian_wether)

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [4]:
usa_weather = pd.DataFrame({  "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})

In [5]:
print(usa_weather)

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [7]:
df = pd.concat([indian_wether,usa_weather])
print(df)

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [8]:
df = pd.concat([indian_wether,usa_weather],ignore_index=True)
print(df)

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

In [9]:
df = pd.concat([indian_wether,usa_weather],keys=['India','USA'])
print(df)

             city  temperature  humidity
India 0    mumbai           32        80
      1     delhi           45        60
      2  banglore           30        78
USA   0  new york           21        68
      1   chicago           14        65
      2   orlando           35        75

In [14]:
df.loc['India']

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [15]:
df.loc['USA']

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [16]:
temperature_df = pd.DataFrame({'city': ["mumbai","delhi","banglore"],
                              'temperature' : [32,45,30]},
                              index=[0,1,2])
print(temperature_df)

       city  temperature
0    mumbai           32
1     delhi           45
2  banglore           30

In [17]:
windspeed_df = pd.DataFrame({'city' : ["delhi","mumbai"],
                             'windspeed' : [7,12]},
                             index=[1,0])
print(windspeed_df)

     city  windspeed
1   delhi          7
0  mumbai         12

In [18]:
df = pd.concat([temperature_df,windspeed_df],axis=1)
print(df)

       city  temperature    city  windspeed
0    mumbai           32  mumbai       12.0
1     delhi           45   delhi        7.0
2  banglore           30     NaN        NaN

In [19]:
pd.concat([temperature_df,windspeed_df])

       city  temperature  windspeed
0    mumbai         32.0        NaN
1     delhi         45.0        NaN
2  banglore         30.0        NaN
1     delhi          NaN        7.0
0    mumbai          NaN       12.0

In [20]:
temp_df = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
})
print(temp_df)

       city  temperature
0  new york           21
1   chicago           14
2   orlando           35

In [21]:
humidity_df = pd.DataFrame({
    "city": ["chicago","new york","orlando"],
    "humidity": [65,68,75],
})
print(humidity_df)

       city  humidity
0   chicago        65
1  new york        68
2   orlando        75

In [23]:
pd.merge(temp_df,humidity_df,on='city')

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [24]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35, 38],
})
df1

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  baltimore           38

In [25]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "humidity": [65,68,71],
})
df2

        city  humidity
0    chicago        65
1   new york        68
2  san diego        71

In [26]:
pd.merge(df1,df2,on='city',how='inner')

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65

In [27]:
pd.merge(df1,df2,on='city',how='left')

        city  temperature  humidity
0   new york           21      68.0
1    chicago           14      65.0
2    orlando           35       NaN
3  baltimore           38       NaN

In [28]:
pd.merge(df1,df2,on='city',how='right')

        city  temperature  humidity
0    chicago         14.0        65
1   new york         21.0        68
2  san diego          NaN        71

In [29]:
pd.merge(df1,df2,on='city',how='outer')

        city  temperature  humidity
0  baltimore         38.0       NaN
1    chicago         14.0      65.0
2   new york         21.0      68.0
3    orlando         35.0       NaN
4  san diego          NaN      71.0

In [31]:
pd.merge(df1,df2,how='cross')

       city_x  temperature     city_y  humidity
0    new york           21    chicago        65
1    new york           21   new york        68
2    new york           21  san diego        71
3     chicago           14    chicago        65
4     chicago           14   new york        68
5     chicago           14  san diego        71
6     orlando           35    chicago        65
7     orlando           35   new york        68
8     orlando           35  san diego        71
9   baltimore           38    chicago        65
10  baltimore           38   new york        68
11  baltimore           38  san diego        71